### ISSUE TITLE
Digital Jul 2020 - Julkort från Bord 5

### ISSUE THREAD

**Issue by mskyttner** [Redpill-Linpro/xmas#1]
![digitalt-julkort](https://user-images.githubusercontent.com/1715840/102521143-d9e60500-4094-11eb-8d6b-3263abc02b1e.png)

**Comment by chrysophylax** [comment]
Feature request: Can rundgång be added?

**Comment by mskyttner** [comment]
Kommer i nästa version!

**Comment by jrogby** [comment]
https://www.youtube.com/watch?v=a0yonO4GWgc

**Comment by EfraimRamsen** [comment]
Kan man lägga till lite mer tomtebuggar?

**Comment by mskyttner** [comment]
Tomtegubbar eller tomtebuggar? Eller skumma tomtar?

**Comment by jrogby** [comment]
Adda skål till backlog!

**Comment by EfraimRamsen** [comment]
Adda matrester till freezer
